# Generated by Django 5.0.2 on 2024-02-19 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_video_file_video_video_alter_video_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
