# Generated by Django 4.1.2 on 2024-03-30 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_video_duration_remove_video_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='size',
            field=models.FloatField(default=0.0),
        ),
    ]
