# Generated by Django 4.1.2 on 2024-03-30 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_video_duration_remove_video_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_name',
            field=models.CharField(default='NO Name', max_length=255),
            preserve_default=False,
        ),
    ]
