# Generated by Django 4.1.2 on 2024-03-30 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_video_video_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
