# Generated by Django 5.0.4 on 2024-04-08 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_userprofile_age_userprofile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_path',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
